version: '2'

volumes:
  traccar:

services:
  traccardb:
    container_name: traccardb
    hostname: traccardb
    image: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./traccar/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  traccar:
    container_name: traccar
    hostname: traccar
    image: traccar/traccar:latest
    restart: unless-stopped
    ports:
      - 8082:8082
      - 5000-5150:5000-5150
      - 5000-5150:5000-5150/udp
    links:
      - traccardb
    volumes:
      - ./traccar/logs:/opt/traccar/logs:rw
      - ./traccar/config/traccar.xml:/opt/traccar/conf/traccar.xml:ro
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    links:
      - traccar
    volumes:
      - ./traccar/config/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - traccar
